#!/bin/bash
#
# pipeline.sh — runs Terraform then Ansible in strict sequence, extracting
# server host+port into the Ansible inventory in between.
#
# Docker Desktop path: every server is reachable at 127.0.0.1 on its own
# published SSH port (Docker Desktop's daemon runs in its own hidden WSL2
# VM, so container bridge IPs aren't reachable from this host directly).

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="${ROOT_DIR}/terraform"
ANSIBLE_DIR="${ROOT_DIR}/ansible"
INVENTORY="${ANSIBLE_DIR}/inventory.ini"

log() { printf '\n==> %s\n' "$1"; }
fail() { printf '\n!! pipeline.sh FAILED: %s\n' "$1" >&2; exit 1; }

log "Checking MinIO is reachable"
MINIO_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:9000/minio/health/live || true)
[ "$MINIO_STATUS" = "200" ] || fail "MinIO not reachable at localhost:9000 (got HTTP ${MINIO_STATUS}). Start it with: docker start minio"

log "Terraform init"
(cd "$TF_DIR" && terraform init -input=false) || fail "terraform init failed"

log "Terraform apply"
(cd "$TF_DIR" && terraform apply -auto-approve -input=false) || fail "terraform apply failed"

log "Extracting server host/port from Terraform output"
API_IP=$(cd "$TF_DIR" && terraform output -raw api_server_ip)             || fail "could not read api_server_ip"
API_PORT=$(cd "$TF_DIR" && terraform output -raw api_server_port)         || fail "could not read api_server_port"
PAYMENTS_IP=$(cd "$TF_DIR" && terraform output -raw payments_server_ip)   || fail "could not read payments_server_ip"
PAYMENTS_PORT=$(cd "$TF_DIR" && terraform output -raw payments_server_port) || fail "could not read payments_server_port"
LOGS_IP=$(cd "$TF_DIR" && terraform output -raw logs_server_ip)           || fail "could not read logs_server_ip"
LOGS_PORT=$(cd "$TF_DIR" && terraform output -raw logs_server_port)       || fail "could not read logs_server_port"

log "Writing inventory.ini"
cat > "$INVENTORY" <<EOI
# Generated by pipeline.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) — do not hand-edit.
[kijanikiosk]
kk-api      ansible_host=${API_IP} ansible_port=${API_PORT}
kk-payments ansible_host=${PAYMENTS_IP} ansible_port=${PAYMENTS_PORT}
kk-logs     ansible_host=${LOGS_IP} ansible_port=${LOGS_PORT}

[kijanikiosk:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
EOI

log "Waiting for SSH to come up on all three hosts"
for entry in "${API_IP}:${API_PORT}" "${PAYMENTS_IP}:${PAYMENTS_PORT}" "${LOGS_IP}:${LOGS_PORT}"; do
  ip="${entry%%:*}"
  port="${entry##*:}"
  tries=0
  until ssh -i ~/.ssh/id_rsa -p "$port" -o StrictHostKeyChecking=no -o ConnectTimeout=3 \
      "root@${ip}" true 2>/dev/null; do
    tries=$((tries + 1))
    [ "$tries" -ge 20 ] && fail "SSH never came up on ${ip}:${port}"
    sleep 3
  done
done

log "Running Ansible playbook"
(cd "$ANSIBLE_DIR" && ansible-playbook -i inventory.ini kijanikiosk.yml) || fail "ansible-playbook failed"

log "Pipeline complete."
