#!/bin/bash
#
# pipeline.sh — runs Terraform then Ansible in strict sequence, extracting
# server IPs into the Ansible inventory in between. Requirement 3.
# Exits non-zero if either stage fails (Requirement 3, criterion 2).
#
# Docker path: IPs come straight from `terraform output`, since the docker
# provider populates container IPs synchronously — no polling script needed
# (unlike the original Multipass design, which needed an external-data-source
# shim because Multipass assigns IPs after the resource already "exists").

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="${ROOT_DIR}/terraform"
ANSIBLE_DIR="${ROOT_DIR}/ansible"
INVENTORY="${ANSIBLE_DIR}/inventory.ini"

log() { printf '\n==> %s\n' "$1"; }
fail() { printf '\n!! pipeline.sh FAILED: %s\n' "$1" >&2; exit 1; }

# ---------- Pre-flight: MinIO must be reachable before Terraform init ----------
log "Checking MinIO is reachable"
MINIO_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:9000/minio/health/live || true)
[ "$MINIO_STATUS" = "200" ] || fail "MinIO not reachable at localhost:9000 (got HTTP ${MINIO_STATUS}). Start it with: docker start minio"

# ---------- Stage 1: Terraform ----------
log "Terraform init"
(cd "$TF_DIR" && terraform init -input=false) || fail "terraform init failed"

log "Terraform apply"
(cd "$TF_DIR" && terraform apply -auto-approve -input=false) || fail "terraform apply failed"

# ---------- Stage 2: extract IPs, write inventory ----------
log "Extracting server IPs from Terraform output"
API_IP=$(cd "$TF_DIR" && terraform output -raw api_server_ip)           || fail "could not read api_server_ip"
PAYMENTS_IP=$(cd "$TF_DIR" && terraform output -raw payments_server_ip)  || fail "could not read payments_server_ip"
LOGS_IP=$(cd "$TF_DIR" && terraform output -raw logs_server_ip)          || fail "could not read logs_server_ip"

[ -n "$API_IP" ] && [ -n "$PAYMENTS_IP" ] && [ -n "$LOGS_IP" ] || fail "one or more IPs came back empty"

log "Writing inventory.ini"
cat > "$INVENTORY" <<EOF
# Generated by pipeline.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) — do not hand-edit.
[kijanikiosk]
kk-api      ansible_host=${API_IP}
kk-payments ansible_host=${PAYMENTS_IP}
kk-logs     ansible_host=${LOGS_IP}

[kijanikiosk:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
EOF

# ---------- Stage 3: SSH readiness ----------
log "Waiting for SSH to come up on all three hosts"
for ip in "$API_IP" "$PAYMENTS_IP" "$LOGS_IP"; do
  tries=0
  until ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o ConnectTimeout=3 \
      "root@${ip}" true 2>/dev/null; do
    tries=$((tries + 1))
    [ "$tries" -ge 20 ] && fail "SSH never came up on ${ip} — check container logs with: docker logs kijanikiosk-<name>"
    sleep 3
  done
done

# ---------- Stage 4: Ansible ----------
log "Running Ansible playbook"
(cd "$ANSIBLE_DIR" && ansible-playbook -i inventory.ini kijanikiosk.yml) || fail "ansible-playbook failed"

log "Pipeline complete."
